### ISSUE TITLE
ScrollView inside Animated.View 

### ISSUE THREAD

**Issue by pacikav** [nathvarun/React-Native-Layout-Tutorial-Series#3]
Hi Varun
I saw this great tutorial on youtube, and this helped me understand animation stuff on React Native.
I'm trying replicate Shapr app functionality where each card have rich content inside
https://giphy.com/gifs/jamWrTnF7wT2gCRqps
For this I placed `ScrollView` inside with `Animate.View` but it does not work. 
Can you help me with some advise?
I'll post code if you have time for this.

**Comment by nathvarun** [comment]
An animated view is similar to a regular view. Share a link to your code so that i can help.

**Comment by DanMCX** [comment]
Have you found a solution for that? I have the same problem.

**Comment by AlexandreSenpai** [comment]
Have you guys found any solutions? My horizontal scroll view doesnt works inside of an animated view... I really dont know what to do.

**Comment by purut18** [comment]
Did you manage to find the solution for this?

**Comment by pacikav** [comment]
It's not actual now
